// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBvfaRCzFw8JZRPfS81gMQoAl28jYKxtg',
    appId: '1:950425287962:web:2ca84a0b9453673c2800a3',
    messagingSenderId: '950425287962',
    projectId: 'cookos',
    authDomain: 'cookos.firebaseapp.com',
    storageBucket: 'cookos.appspot.com',
    measurementId: 'G-NER2DMKRPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzkKRdRNVNQPIlXOWBPEdRg7RlfMHY9ug',
    appId: '1:950425287962:android:39a1e547700194512800a3',
    messagingSenderId: '950425287962',
    projectId: 'cookos',
    storageBucket: 'cookos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3RHuxnyM6RF7F4fp94EYRV4CFy2jDhXs',
    appId: '1:950425287962:ios:e2f0dc7b5f70e0472800a3',
    messagingSenderId: '950425287962',
    projectId: 'cookos',
    storageBucket: 'cookos.appspot.com',
    iosBundleId: 'com.example.flutterDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3RHuxnyM6RF7F4fp94EYRV4CFy2jDhXs',
    appId: '1:950425287962:ios:a3b84bcdf3338a162800a3',
    messagingSenderId: '950425287962',
    projectId: 'cookos',
    storageBucket: 'cookos.appspot.com',
    iosBundleId: 'com.example.flutterDev.RunnerTests',
  );
}
